# Generated by Django 5.1.1 on 2024-10-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_agreement_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metervalue',
            name='value',
        ),
        migrations.AddField(
            model_name='metervalue',
            name='value_fact',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metervalue',
            name='value_invoice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='metervalue',
            name='date_add',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='metervalue',
            name='value_first',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='metervalue',
            name='value_last',
            field=models.FloatField(null=True),
        ),
    ]
