# Generated by Django 5.1.1 on 2024-10-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_oil'),
    ]

    operations = [
        migrations.AddField(
            model_name='oil',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
