# Generated by Django 5.1.1 on 2024-10-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_oil_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='metervalue',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
