# Generated by Django 5.1.2 on 2024-10-18 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_metervalue_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metervalue',
            old_name='number_meter',
            new_name='id_meter',
        ),
    ]
