# Generated by Django 5.1.2 on 2024-10-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_number_meter_metervalue_id_meter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metervalue',
            name='value_invoice',
        ),
    ]
