# Generated by Django 5.1.2 on 2024-10-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_metervalue_value_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metervalue',
            old_name='id_meter',
            new_name='meter',
        ),
        migrations.RenameField(
            model_name='metervalue',
            old_name='id_palse',
            new_name='palse',
        ),
    ]
